config/routes.rb
Rails.application.routes.draw do
  get 'search/jobs'
  get 'search/volunteers'
  get 'search/posters'

  root 'jobs#index'
  devise_for :users, :controllers => 
                      { omniauth_callbacks: "omniauth/omniauth_callbacks" }

  resources :jobs, only: [:index, :show] do
    get 'search', on: :collection
    get 'distance', on: :collection
  end

  get 'posts' => 'posts#index', as: "posts_index"
  scope 'user/:user_name.:user_id' do
    resources :posts, only: [:show, :create, :update, :destroy, :edit] do
      resources :comments, only: [:create, :update, :edit, :destroy]
    end
    post 'request_friend', controller: 'users'
    post 'cancel_request', controller: 'users'
    post 'accept_friend', controller: 'users'
    post 'remove_friend', controller: 'users'
    delete 'destroy', controller: 'users'
  end


  # User
  get '/admin' => "users#index", as: :admin_users
  get '/user/:user_name.:user_id' => "users#show", as: :user_profile

  # google verification
  get '/google6cd96f3e20442b00.html' => 'google_verification#index'

  get '*path' => redirect('/')
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def jobs
    @per_page = params[:per_page] ? params[:per_page] : 10
    @jobs = Job.search(params[:target]).paginate(page: params[:page], per_page: @per_page).order(:id)
    @hash = get_map_hash
  end

  def volunteers
    @per_page = params[:per_page] ? params[:per_page] : 10
    @volunteers = User.search(params[:target]).paginate(page: params[:page], per_page: @per_page).order(:id)
  end

  def posters
    @per_page = params[:per_page] ? params[:per_page] : 10
    @posts = Post.search(params[:target]).paginate(page: params[:page], per_page: @per_page).order(:id)
  end

  private
  def get_map_hash
    Gmaps4rails.build_markers(@jobs) do |job, marker|
      marker.json({id: job.id})
      marker.lat job.lat
      marker.lng job.lng
      marker.infowindow %(#{job.title}<br>地址： #{job.location})
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_search.html.erb
<h1>搜尋 '<%= params[:target] %>'</h1>
<div class="row">
  <div class="col-md-3">
    <br>
    <ul class="nav nav-pills nav-stacked">
      <li role="presentation" class=<%= 'active' if current_page?(search_jobs_path) %>>
        <%= link_to "找志工服務", search_jobs_path(target: params[:target]) %>
      </li>
      <li role="presentation" class=<%= 'active' if current_page?(search_volunteers_path) %>>
        <%= link_to "找志工", search_volunteers_path(target: params[:target]) %>
      </li>
      <li role="presentation" class=<%= 'active' if current_page?(search_posters_path) %>>
        <%= link_to "找文章", search_posters_path(target: params[:target]) %>
      </li>
    </ul>
  </div>
  <div class="col-md-9">
    <%= yield :search_body %>
  </div>
</div>

app/views/search/jobs.html.erb
<% content_for :search_body do %>
  <%= will_paginate @jobs, style: "align-text: center;" %>
  <div id="map" style='width: 100%; height: 500px;'></div>
  <br>
  <table class="table table-striped table-hover table-condense"> 
    <thead> 
      <tr class="info"> 
        <td> 最新更新 </td>
        <td> 志工服務 </td>
        <td> 地點 </td>
      </tr>
    </thead>
    <tbody> 
    <%= render partial: 'jobs/job_list', collection: @jobs, as: :job, locals: {length: 26} %>
    </tbody>
  </table>
  <%= will_paginate @jobs, style: "align-text: center;" %>
<% end %>

<%= render 'search' %>

<script type="text/javascript">
  initGmaps(<%= raw @hash.to_json %>)
</script>

app/views/search/posters.html.erb
<%= content_for :search_body do %>
  <%= will_paginate @posts, style: "align-text: center;" %>
  <%= render partial: 'posts/post_list', collection: @posts, as: :post, locals: {show_comment: false} %>
  <%= will_paginate @posts, style: "align-text: center;" %>
<% end %>

<%= render 'search' %>

app/views/search/volunteers.html.erb
<% content_for :search_body do %>
  <table class="table table-striped"> 
    <thead> 
      <tr> 
        <td> 名稱 </td>
        <td> 狀態 </td>
        <td> </td>
      </tr>
    </thead>
    <tbody> 
      <%= render partial: 'users/volunteer_list', collection: @volunteers, as: :volunteer %>
    </tbody>
  </table>
<% end %>

<%= render 'search' %>