config/routes.rb
Rails.application.routes.draw do
  get 'search/jobs'
  get 'search/volunteers'
  get 'search/posters'

  root 'jobs#index'
  devise_for :users, :controllers => 
                      { omniauth_callbacks: "omniauth/omniauth_callbacks" }

  resources :jobs, only: [:index, :show] do
    get 'search', on: :collection
    get 'distance', on: :collection
  end

  get 'posts' => 'posts#index', as: "posts_index"
  scope 'user/:user_name.:user_id' do
    resources :posts, only: [:show, :create, :update, :destroy, :edit] do
      resources :comments, only: [:create, :update, :edit, :destroy]
    end
    post 'request_friend', controller: 'users'
    post 'cancel_request', controller: 'users'
    post 'accept_friend', controller: 'users'
    post 'remove_friend', controller: 'users'
    delete 'destroy', controller: 'users'
  end


  # User
  get '/admin' => "users#index", as: :admin_users
  get '/user/:user_name.:user_id' => "users#show", as: :user_profile

  # google verification
  get '/google6cd96f3e20442b00.html' => 'google_verification#index'

  get '*path' => redirect('/')
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, presence: true
  validates :joburl, presence: true

  geocoded_by :location,
    latitude: :lat, longitude: :lng
  after_validation :geocode

  scope :search, ->(target) { where("title like ? or content like ? or location like ?",
                                    "%#{target}%", "%#{target}%", "%#{target}%") }
  scope :distance_from, ->(location) { near(location, 10, {unit: :km}).order("distance") }
  scope :paginator, ->(page, per_page) { paginate(page: page, per_page: per_page).order(:id) }
  scope :paginator_recent, ->(page, per_page) { paginate(page: page, per_page: per_page).order(last_modified: :desc) }
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @per_page = params[:per_page] ? params[:per_page] : 10
    @page = params[:page]
    if @location = params[:location]
      distance
    elsif @target = params[:target]
      search
    else
      @jobs = Job.paginator_recent(@page, @per_page)
      @hash = get_map_hash
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def search
    @per_page = params[:per_page] ? params[:per_page] : 10
    @jobs = Job.search(params[:target]).paginate(page: params[:page], per_page: @per_page).order(:id)
    @hash = get_map_hash
    render :index
  end

  def distance
    @per_page = params[:per_page] ? params[:per_page] : 10
    @location = params[:location]
    @page = params[:page]
    @jobs = Job.distance_from(@location).paginator(@page, @per_page)
    @hash = get_map_hash
    render :index
  end

  private
  def get_map_hash
    Gmaps4rails.build_markers(@jobs) do |job, marker|
      marker.json({id: job.id})
      marker.lat job.lat
      marker.lng job.lng
      marker.infowindow %(#{job.title}<br>地址： #{job.location})
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job_list.html.erb
<tr id=<%= job.id %>> 
  <td> <%= job.last_modified.strftime("%m/%e, %Y") %> </td>
  <td> <%= link_to truncate(job.title, length: length), job_path(job) %> </td>
  <td> <%= truncate(job.location, length: length) %> </td>
</tr>

app/views/jobs/index.html.erb
<div class="row">
  <div class="col-md-7">
    <h1><strong> 黎明志工銀行 </strong></h1>
  </div>
  <div class="col-md-5">
    <br />
    <%= bootstrap_form_tag url: distance_jobs_path, method: :get do |f| %>
      <%= f.text_field :location, hide_label: true, 
        placeholder: '輸入地點透過距離排序（例如"台北大安區"）',
        value: params[:location], icon: "road" %>
    <% end %>
  </div>
</div>
<%= flash_tag %>

<div class="row">
  <!-- Map -->
  <div class="col-md-7">
    <div id="map" style='width: 100%; height: 500px;'></div>
  </div><!-- /col -->

  <div class="col-md-5">
    <!-- Pager -->
    Show: (<%= @per_page %>) 
    <% for per_page in [5, 10, 20, 30, 50] %>
      | <%= link_to per_page, jobs_path(per_page: per_page, location: params[:location], target: params[:target])%>
    <% end %><br />
    <%= will_paginate @jobs, style: "align-text: center;" %>
    <!-- Job Table -->
    <table class="table table-striped table-hover table-condense"> 
      <thead> 
        <tr class="info"> 
          <td> 最新更新 </td>
          <td> 志工服務 </td>
          <td> 地點 </td>
        </tr>
      </thead>
      <tbody> 
      <%= render partial: 'job_list', collection: @jobs, as: :job, locals: {length: 13} %>
      </tbody>
    </table>
  </div><!-- /col -->
</div><!-- /row -->

<script type="text/javascript">
  initGmaps(<%= raw @hash.to_json %>)
</script>

app/views/jobs/show.html.erb
<h1><%= @job.title %> </h1>                                                                                                                
<p>來源：<%= link_to '104人力銀行', @job.joburl %></p>
<p> 更新日期： <%= @job.last_modified.strftime("%m/%e %a, %Y") %> </p>
<h2>簡介</h2>
<table>
  <tr><td>工作內容： <%= @job.content %></td></tr>
  <tr><td>工作待遇： <%= @job.treatment %></td></tr>
  <tr><td>工作性質： <%= @job.jobtype %></td></tr>
  <tr><td>工作地點： <%= @job.location %></td></tr>
  <tr><td>上班時段： <%= @job.worktime %></td></tr>
  <tr><td>休假制度： <%= @job.leavesys %></td></tr>
  <tr><td>可上班日： <%= @job.availability %></td></tr>
  <tr><td>需求人數： <%= @job.reqnum %></td></tr>
</table>
<h2>工作條件</h2>
<table>
  <tr><td>接受身份： <%= @job.acceptid %></td></tr>
  <tr><td>工作經歷： <%= @job.exp %></td></tr>
  <tr><td>學歷要求： <%= @job.education %></td></tr>
  <tr><td>科系要求： <%= @job.department %></td></tr>
  <tr><td>語文條件： <%= @job.language %></td></tr>
  <tr><td>擅長工具： <%= @job.tool %></td></tr>
  <tr><td>工作技能： <%= @job.skill %></td></tr>
  <tr><td>其它條件： <%= @job.othercond %></td></tr>
</table>
<h2>應徵方式</h2>
<table>
  <tr><td>連絡人： <%= @job.contact %></td></tr>
  <tr><td>E-mail： <embed height="26" wmode="transparent" src="<%= @job.emailsrc %>"></td></tr>
  <tr><td>電洽： <%= image_tag(@job.telesrc) %></td></tr>
  <tr><td>親洽： <%= @job.inperson %></td></tr>
  <tr><td>其它： <%= @job.other %></td></tr>
</table>