config/routes.rb
Rails.application.routes.draw do
  get 'search/jobs'
  get 'search/volunteers'
  get 'search/posters'

  root 'jobs#index'
  devise_for :users, :controllers => 
                      { omniauth_callbacks: "omniauth/omniauth_callbacks" }

  resources :jobs, only: [:index, :show] do
    get 'search', on: :collection
    get 'distance', on: :collection
  end

  get 'posts' => 'posts#index', as: "posts_index"
  scope 'user/:user_name.:user_id' do
    resources :posts, only: [:show, :create, :update, :destroy, :edit] do
      resources :comments, only: [:create, :update, :edit, :destroy]
    end
    post 'request_friend', controller: 'users'
    post 'cancel_request', controller: 'users'
    post 'accept_friend', controller: 'users'
    post 'remove_friend', controller: 'users'
    delete 'destroy', controller: 'users'
  end


  # User
  get '/admin' => "users#index", as: :admin_users
  get '/user/:user_name.:user_id' => "users#show", as: :user_profile

  # google verification
  get '/google6cd96f3e20442b00.html' => 'google_verification#index'

  get '*path' => redirect('/')
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User", foreign_key: :user_id

  validates :title, presence: true
  validates :content, presence: true

  has_many :comments, dependent: :destroy

  scope :recent, -> { order("created_at DESC") }
  scope :search, ->(target) { where("title like ? or content like ?",
                                    "%#{target}%", "%#{target}%") }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_user, except: [:index]
  def index
    @per_page = params[:per_page] ? params[:per_page] : 10
    @posts = Post.all.paginate(page: params[:page], per_page: @per_page).recent
  end

  def show
    @post = @user.posts.find(params[:id])
    @comment = @post.comments.new
  end

  def edit
    @post = @user.posts.find(params[:id])
    unless current_user==@post.author || current_user.try(:admin)
      redirect_to post_path(@user.name, @user, @post)
    end
  end

  def update
    @post = @user.posts.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "成功修改文章"
    else
      m = "文章修改失敗，"
      @post.errors.messages.each do |e|
        m << e.join(", ") << " "
      end
      flash[:alert] = m
    end
    redirect_to user_profile_path(@user.name, @user.id)
  end

  def create
    @post = @user.posts.new(post_params)
    if @post.save
      flash[:notice] = "成功發佈文章"
    else
      m = "文章發佈失敗，"
      @post.errors.messages.each do |e|
        m << e.join(", ") << " "
      end
      flash[:alert] = m
    end
    redirect_to user_profile_path(@user.name, @user.id)
  end

  def destroy
    @post = @user.posts.find(params[:id])
    @post.destroy
    flash[:warning] = "文章已成功刪除"
    redirect_to user_profile_path(@user.name, @user.id)
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_user
    @user = User.find(params[:user_id]) 
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= bootstrap_form_for [@post, @post.comments.new], url: post_comments_path(@post.author, @post.author, @post, @comment) do |f| %>
  <%= current_user_image_tag %>
  <%= user_tag %>
  <%= f.text_field :content, hide_label: true, placeholder: "留言...", icon: "pencil" %>
  <%= f.submit "留言" %>
<% end %>

app/views/posts/_comment_list.html.erb
<div class="media">
  <!-- Commenter Image -->
  <div class="pull-left">
  <%= link_user_image_tag comment.commenter %>
  </div>
  <!-- Delete Comment -->
  <% if current_user==comment.commenter || current_user.try(:admin) %>
    <div class="btn-group pull-right">
      <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" role="button" >
        <i class="glyphicon glyphicon-cog"></i> <span class="caret"></span></button>
      <ul class="dropdown-menu" role="menu">
        <li> <%= link_to "刪除留言", post_comment_path(comment.commenter, comment.commenter.id, comment.post, comment), method: :delete, data: { confirm: "確定刪除？"} %> </li>
      </ul>
    </div>
  <% end %>
  <div class="media-body">
    <!-- Commenter and Date -->
    <p> <%= link_to comment.commenter.name, user_profile_path(comment.commenter.name, comment.commenter.id) %>
      <small style="color: #aaaaaa;"> <%= comment.created_at.localtime.strftime("%m/%d %a, %Y at %R") %> </small>
    </p>
    <!-- Comment Body -->
    <%= simple_format comment.content %>
  </div>
</div>

app/views/posts/_post_list.html.erb
<div class="row">
  <div class="col-md-8">
    <!-- Post Title -->
    <h2 class="blog-post-title"> <%= link_to post.title, post_path(post.author.name, post.author.id, post) %> </h2>
    <!-- Edit/Delete Button -->
    <% if current_user==post.author || current_user.try(:admin) %>
      <div class="btn-group pull-right">
        <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" role="button" >
          <i class="glyphicon glyphicon-cog"></i> <span class="caret"></span></button>
        <ul class="dropdown-menu" role="menu">
          <li> <%= link_to "編輯文章", edit_post_path(post.author.name, post.author.id, post) %> </li>
          <li class="divider"></li>
          <li> <%= link_to "刪除文章", post_path(post.author.name, post.author.id , post), method: :delete, data: { confirm: "確定刪除？"} %> </li>
        </ul>
      </div>
    <% end %>
    <!-- Author / Date -->
    <p> 
      <%= link_user_image_tag post.author %>
      <%= link_to post.author.name, user_profile_path(post.author.name, post.author.id) %>
    </p>
    <!-- Post Body -->
    <p class="blog-post-meta"> <%= post.created_at.localtime.strftime("%R %m/%d %a, %Y") %> </p>
    <%= simple_format truncate(post.content, length: 300) %>
    <% if post.content.length > 300 %>
      <p> <%= link_to "繼續閱讀", post_path(post.author.name, post.author.id, post) %> </p>
    <% end %>


    <!-- Comments -->
    <% if show_comment %>
      <div class="well">
        <%= flash_tag %>
        <%= render partial: 'posts/comment_list', collection: post.comments.where('id >= 0'), as: :comment %>
        <hr>
        <% if current_user %>
          <% @post = post %>
          <%= render 'posts/comment_form' %>
        <% else %>
          <br>
          <%= render text: "登入後可留言" %>
        <% end %>
      </div>
    <% end %>
    <hr>
  </div>
</div>

app/views/posts/edit.html.erb
<h1> 編輯 <%= @post.title %> </h1>
<div class="row">
  <div class="col-md-8">
<%= bootstrap_form_for [@user, @post], url: post_path(@user.name, @user.id, @post), method: :patch do |f| %>
  <%= f.text_field :title, label: "標題：" %>
  <%= f.text_area :content, style: "height: 200px;", label: "內文：" %>
  <%= f.submit "變更", class: "btn btn-primary" %>
  <%= link_to "取消", user_profile_path(@post.author.name, @post.author.id), class: "btn btn-default pull-right" %>
<% end %>
</div>
</div>

app/views/posts/index.html.erb
<h1> 志工文章 </h1>

<%= will_paginate @posts, style: "align-text: center;" %>
<%= render( partial: 'post_list', collection: @posts, as: :post, locals: {show_comment: true}) || "尚未發佈任何文章" %>
<%= will_paginate @posts, style: "align-text: center;" %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8">
    <!-- Post Title -->
    <h2 class="blog-post-title"> <%= @post.title %> </h2>
    <!-- Edit/Delete Button -->
    <% if current_user==@post.author || current_user.try(:admin) %>
      <div class="btn-group pull-right">
        <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" role="button" >
          <i class="glyphicon glyphicon-cog"></i> <span class="caret"></span></button>
        <ul class="dropdown-menu" role="menu">
          <li> <%= link_to "編輯文章", edit_post_path(@post.author.name, @post.author.id, @post) %> </li>
          <li class="divider"></li>
          <li> <%= link_to "刪除文章", post_path(@post.author.name, @post.author.id , @post), method: :delete, data: { confirm: "確定刪除？"} %> </li>
        </ul>
      </div>
    <% end %>
    <!-- Author / Date -->
    <p> 
      <%= link_user_image_tag @post.author %>
      <%= link_to @post.author.name, user_profile_path(@post.author.name, @post.author.id) %>
    </p>
    <!-- Post Body -->
    <p class="blog-post-meta"> <%= @post.created_at.localtime.strftime("%R %m/%d %a, %Y") %> </p>
    <%= simple_format @post.content %><br />

    <!-- comments -->
    <div class="well">
      <%= flash_tag %>
      <%= render partial: 'comment_list', collection: @post.comments.where('id >= 0'), as: :comment %>
      <hr>
      <% if current_user %>
        <%= render 'comment_form' %>
      <% else %>
        <br>
        <%= render text: "登入後可留言" %>
      <% end %>
    </div>
  </div>
</div><!-- row -->