config/routes.rb
Rails.application.routes.draw do
  get 'search/jobs'
  get 'search/volunteers'
  get 'search/posters'

  root 'jobs#index'
  devise_for :users, :controllers => 
                      { omniauth_callbacks: "omniauth/omniauth_callbacks" }

  resources :jobs, only: [:index, :show] do
    get 'search', on: :collection
    get 'distance', on: :collection
  end

  get 'posts' => 'posts#index', as: "posts_index"
  scope 'user/:user_name.:user_id' do
    resources :posts, only: [:show, :create, :update, :destroy, :edit] do
      resources :comments, only: [:create, :update, :edit, :destroy]
    end
    post 'request_friend', controller: 'users'
    post 'cancel_request', controller: 'users'
    post 'accept_friend', controller: 'users'
    post 'remove_friend', controller: 'users'
    delete 'destroy', controller: 'users'
  end


  # User
  get '/admin' => "users#index", as: :admin_users
  get '/user/:user_name.:user_id' => "users#show", as: :user_profile

  # google verification
  get '/google6cd96f3e20442b00.html' => 'google_verification#index'

  get '*path' => redirect('/')
end

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div id="navbar" class="navbar-collapse collapse">
      <!-- left -->
      <ul class="nav navbar-nav">
        <%= nav_link_to "黎明志工銀行", root_path, path_controller: "jobs", icon: "home" %>
        <%= nav_link_to "志工文章", posts_index_path, path_controller: "posts", icon: "list-alt" %>
        <li> <%= render 'layouts/search_bar' %> </li>
      </ul>
      <!-- right -->
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.try(:admin) %>
        <li> <%= link_to "Users", admin_users_path %> </li>
        <% end %>
        <li> <%= current_user_image_tag %> </li>
        <li> <%= nav_user_tag %> </li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >
            <i class="glyphicon glyphicon-cog"></i> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% if current_user.provider == "dawnbank" %>
                <li> <%= link_to "編輯個人帳戶", edit_user_registration_path %> </li>
              <% end %>
              <li> <%= link_to "編輯個人資訊", "#"  %> </li>
              <li class="divider"></li>
              <li> <%= link_to "登出", destroy_user_session_path, method: :delete %> </li>
            </ul>
          </li>
        <% end %>
        <%= signup_tag %>
        <%= login_tag %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/ container -->
</nav>

app/views/layouts/_search_bar.html.erb
<%= form_tag( searchPath, method: :get, class: "navbar-form navbar-left" ) do %>
  <%= text_field_tag(:target, nil, placeholder: "當志工、找志工、找文章", value: params[:target], class: "form-control", style: "width: 210px;") %>
  <%= button_tag(type: "submit", class: "btn btn-default") do %>
    <i class="glyphicon glyphicon-search"></i>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>黎明志工銀行</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="author" content="jKodrum">
  <meta name="description" content="黎明志工銀行，適地性志工平台">
  <meta property="og:title" content="黎明志工銀行">
  <meta property="og:url" content="https://dawnbank.herokuapp.com">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <br>
  <!-- Main component for a primary marketing message or call to action -->
  <div class="">
    <%= yield %>
  </div>
</div> <!-- /container -->


</body>
</html>